---
permalink: online-help/concept-fixing-ontap-issues-directly-from-unified-manager.html 
sidebar: sidebar 
keywords: fix it,fix all 
summary: Você pode corrigir certos problemas do ONTAP diretamente na interface de usuário do Unified Manager em vez de usar o Gerenciador de sistema do ONTAP ou a CLI do ONTAP. 
---
= Correção de problemas do ONTAP diretamente do Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode corrigir certos problemas do ONTAP diretamente na interface de usuário do Unified Manager em vez de usar o Gerenciador de sistema do ONTAP ou a CLI do ONTAP.

Um recurso chamado "ações de gerenciamento" fornece correções para vários problemas do ONTAP que acionaram eventos do Unified Manager. As ações de gerenciamento estão disponíveis no Dashboard, na página de detalhes do evento e na seleção Workload Analysis no menu de navegação à esquerda.

Há certos problemas que o Unified Manager faz o diagnóstico completo e fornece uma única resolução. Quando disponíveis, essas resoluções são exibidas em ações de gerenciamento com um botão *Fix it*. Clique no botão *Fix it* para corrigir o problema. Tem de ter a função Administrador de aplicações ou Administrador de armazenamento.

O Unified Manager envia comandos ONTAP ao cluster para fazer a correção solicitada. Quando a correção está concluída, o evento fica obsoleto.

Algumas ações de gerenciamento permitem que você corrija o mesmo problema em vários objetos de armazenamento usando o botão *Fix All*. Por exemplo, pode haver 5 volumes que têm o evento "volume Space Full" que pode ser resolvido clicando na ação de gerenciamento *Fix All* para "'Enable volume crescimento'". Um clique permite que você corrija esse problema em volumes 5.
