---
permalink: online-help/reference-relationship-last-1-month-transfer-status-view.html 
sidebar: sidebar 
keywords:  
summary: 'O modo de exibição relacionamento: Último status de transferência de 1 meses permite analisar as tendências de transferência de volume ao longo de um período de tempo para volumes em relacionamentos assíncronos. Esta página também mostra se a transferência de volume foi um sucesso ou uma falha.' 
---
= Relação: Último 1 mês visualização do Status da transferência
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O modo de exibição relacionamento: Último status de transferência de 1 meses permite analisar as tendências de transferência de volume ao longo de um período de tempo para volumes em relacionamentos assíncronos. Esta página também mostra se a transferência de volume foi um sucesso ou uma falha.

Os controles ao longo da parte superior da página permitem selecionar uma exibição específica (para integridade, desempenho, capacidade e assim por diante), realizar pesquisas para localizar objetos específicos, criar e aplicar filtros para restringir a lista de dados exibidos, adicionar/remover/reordenar colunas na página e exportar os dados na página para um `.csv` arquivo , ou `.xlsx` . `.pdf` Depois de personalizar a página, você pode salvar os resultados como uma visualização personalizada e, em seguida, agendar um relatório desses dados para ser gerado e enviado por e-mail regularmente.

* *Volume da fonte*
+
Exibe o nome do volume de origem.

* *Volume de destino*
+
Apresenta o nome do volume de destino.

* *Tipo de operação*
+
Apresenta o tipo de transferência de volume.

* *Resultado da operação*
+
Apresenta se a transferência de volume foi bem-sucedida.

* *Hora de início da transferência*
+
Apresenta a hora de início da transferência de volume.

* * Tempo de término da transferência*
+
Apresenta a hora de fim da transferência de volume.

* *Duração da transferência*
+
Apresenta o tempo necessário (em horas) para concluir a transferência de volume.

* * Tamanho da transferência*
+
Exibe o tamanho (em MB) do volume transferido.

* *Fonte SVM*
+
Exibe o nome da máquina virtual de storage (SVM).

* *Cluster de origem*
+
Exibe o nome do cluster de origem.

* *SVM de destino*
+
Exibe o nome do SVM de destino.

* *Cluster de destino*
+
Exibe o nome do cluster de destino.


