---
permalink: online-help/reference-backup-settings-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: Defina o agendamento de backup, a contagem de retenção e, ao usar o método de backup de despejo de banco de dados MySQL, o caminho de backup para uma instância selecionada do Unified Manager. 
---
= Caixa de diálogo Configurações de backup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Defina o agendamento de backup, a contagem de retenção e, ao usar o método de backup de despejo de banco de dados MySQL, o caminho de backup para uma instância selecionada do Unified Manager.

Pode alterar as seguintes definições de cópia de segurança da base de dados:

* *Caminho*
+
Quando você estiver usando o método de backup de despejo de banco de dados MySQL, este campo especifica o caminho para o local onde você armazena os arquivos de backup. Ao usar o método de backup instantâneo, esse local mostra o cluster, a VM de armazenamento e o volume no qual o backup será armazenado.

+
A tabela a seguir especifica o formato do caminho de backup e os locais padrão para diferentes sistemas operacionais:

+
|===
| Sistema operacional de host | Formato do caminho de cópia de segurança 


 a| 
Dispositivo virtual
 a| 
`/opt/netapp/data/ocum-backup`



 a| 
Red Hat Enterprise Linux ou CentOS Linux
 a| 
`/data/ocum-backup`



 a| 
Microsoft Windows
 a| 
`C:\ProgramData\NetApp\OnCommandAppData\ocum\backup\`

|===
* *Contagem de retenção*
+
Especifica o número máximo de backups a serem retidos pelo Unified Manager. O valor padrão é 10.

* *Programado diariamente*
+
Especifica a programação diária de backup com a hora.

* *Programado semanalmente*
+
Especifica a programação semanal de backup com o dia e a hora.

* *Nenhuma*
+
Especifica que nenhum backup será criado.


