---
permalink: online-help/reference-snapmirror-and-vault-relationship-events.html 
sidebar: sidebar 
keywords:  
summary: Os eventos de relacionamento com o SnapMirror e o Vault fornecem informações sobre o status dos relacionamentos do SnapMirror assíncrono e do Vault para que você possa monitorar possíveis problemas. Os eventos são agrupados por área de impactos e incluem o nome do evento e da armadilha, o nível de impactos, o tipo de origem e a gravidade. 
---
= Eventos de relacionamento com SnapMirror e Vault
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os eventos de relacionamento com o SnapMirror e o Vault fornecem informações sobre o status dos relacionamentos do SnapMirror assíncrono e do Vault para que você possa monitorar possíveis problemas. Os eventos são agrupados por área de impactos e incluem o nome do evento e da armadilha, o nível de impactos, o tipo de origem e a gravidade.



== Área de impactos: Proteção

|===
| Nome do evento (Nome da armadilha) | Nível de impactos | Tipo de origem | Gravidade 


 a| 
Espelhamento assíncrono e cofre não saudável(ocumEvtMirrorVaultRelationshipUnHealthy)
 a| 
Risco
 a| 
Relação de SnapMirror
 a| 
Aviso



 a| 
Espelhamento assíncrono e Vault quebrado-off(ocumEvtMirrorVaultRelationshipStateBrokenoff)
 a| 
Risco
 a| 
Relação de SnapMirror
 a| 
Erro



 a| 
Falha na inicialização do espelhamento assíncrono e do Vault(ocumEvtMirrorVaultRelationshipInitializeFailed)
 a| 
Risco
 a| 
Relação de SnapMirror
 a| 
Erro



 a| 
Falha na atualização assíncrona do espelho e do Vault(ocumEvtMirrorVaultRelationshipUpdateFailed)
 a| 
Risco
 a| 
Relação de SnapMirror
 a| 
Erro



 a| 
Erro assíncrono do espelhamento e do Vault Lag(ocumEvtMirrorVaultRelationshipLagError)
 a| 
Risco
 a| 
Relação de SnapMirror
 a| 
Erro



 a| 
Espelho assíncrono e Vault Lag Warning(ocumEvtMirrorVaultRelationshipLagWarning)
 a| 
Risco
 a| 
Relação de SnapMirror
 a| 
Aviso



 a| 
Espelhamento assíncrono e Vault Resync falhou(ocumEvtMirrorVaultRelationshipResyncFailed)
 a| 
Risco
 a| 
Relação de SnapMirror
 a| 
Erro

|===