---
permalink: health-checker/task-specifying-the-destination-location-for-snapshot-backups.html 
sidebar: sidebar 
keywords:  
summary: Você configura o local de destino para backups de Snapshot do Unified Manager em um volume que já tenha configurado em um de seus clusters do ONTAP. Você define o local no console de manutenção do Unified Manager. 
---
= Especificando o local de destino para backups Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você configura o local de destino para backups de Snapshot do Unified Manager em um volume que já tenha configurado em um de seus clusters do ONTAP. Você define o local no console de manutenção do Unified Manager.



== Antes de começar

* Você deve ter as credenciais de usuário raiz para o host Linux no qual o Unified Manager está instalado.
* Você deve ter uma ID de usuário e senha autorizados para fazer login no console de manutenção do servidor do Unified Manager.
* Você deve ter o endereço IP de gerenciamento de cluster, o nome da VM de armazenamento, o nome do volume e o nome de usuário e senha do sistema de armazenamento.
* Você precisa ter montado o volume no host do Unified Manager e ter o caminho de montagem.




== Passos

. Usando o Secure Shell, conete-se ao endereço IP ou ao nome de domínio totalmente qualificado do sistema Unified Manager.
. Inicie sessão no sistema com o nome e a palavra-passe do utilizador de manutenção (umadmin).
. Digite o comando `maintenance_console` e pressione Enter.
. No console de manutenção *Menu Principal*, digite o número da opção *Backup Restore*.
. Digite o número para *Configurar cópia de segurança de instantâneo do NetApp*.
. Digite o número para *Configuração para NFS*.
. Revise as informações que você precisará fornecer e insira o número de *Digite os detalhes da configuração de backup*.
. Para identificar o volume em que o instantâneo será gravado, insira o endereço IP da interface de gerenciamento de cluster, o nome da VM de armazenamento, o nome do volume, o nome do usuário e a senha do sistema de armazenamento e o caminho de montagem.
. Verifique essas informações e `y` digite .
+
O sistema executa as seguintes tarefas:

+
** Estabelece a conexão com o cluster
** Pára todos os serviços
** Cria um novo diretório no volume e copia os arquivos de configuração do banco de dados do Unified Manager
** Exclui os arquivos do Unified Manager e cria um link simbólico para o novo diretório do banco de dados
** Reinicia todos os serviços


. Saia do console de manutenção e inicie a interface do Unified Manager para criar a programação de backup do Snapshot se você ainda não tiver feito isso.

