---
permalink: data-protection/reference-relationship-last-1-month-transfer-rate-view.html 
sidebar: sidebar 
keywords:  
summary: 'O modo de exibição relação: Taxa de transferência de 1 meses último permite analisar a quantidade de volume de dados que é transferido diariamente para volumes em relacionamentos assíncronos. Esta página também fornece detalhes sobre transferências diárias de volume e o tempo necessário para concluir a operação de transferência.' 
---
= Relação: Último 1 mês visualização da taxa de transferência
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O modo de exibição relação: Taxa de transferência de 1 meses último permite analisar a quantidade de volume de dados que é transferido diariamente para volumes em relacionamentos assíncronos. Esta página também fornece detalhes sobre transferências diárias de volume e o tempo necessário para concluir a operação de transferência.

Os controles ao longo da parte superior da página permitem selecionar uma exibição específica (para integridade, desempenho, capacidade e assim por diante), realizar pesquisas para localizar objetos específicos, criar e aplicar filtros para restringir a lista de dados exibidos, adicionar/remover/reordenar colunas na página e exportar os dados na página para um `.csv` arquivo , ou `.xlsx` . `.pdf` Depois de personalizar a página, você pode salvar os resultados como uma visualização personalizada e, em seguida, agendar um relatório desses dados para ser gerado e enviado por e-mail regularmente.

* * Tamanho total da transferência*
+
Exibe o tamanho total da transferência de volume em gigabytes.

* *Dia*
+
Apresenta o dia em que a transferência de volume foi iniciada.

* *Hora de fim*
+
Exibe a hora de término da transferência de volume com a data.


